#104 - gcloud fix - add pull/105 later in regr tst
Full regression testing
```
Welcome to Cloud Shell! Type "help" to get started.
To set your Cloud Platform project in this session use “gcloud config set project [PROJECT_ID]”
michael@cloudshell:~$ history
    1  history
    2  ls
    3  history
    4  ls
    5  history
michael@cloudshell:~$ gcloud config set project pubsec-declarative-tk-apgz
Updated property [core/project].
michael@cloudshell:~ (pubsec-declarative-tk-apgz)$ export REGION=northamerica-northeast1
michael@cloudshell:~ (pubsec-declarative-tk-apgz)$ export PROJECT_ID=$(gcloud config list --format 'value(core.project)')
michael@cloudshell:~ (pubsec-declarative-tk-apgz)$ export ORG_ID=$(gcloud projects get-ancestors $PROJECT_ID --format='get(id)' | tail -1)
michael@cloudshell:~ (pubsec-declarative-tk-apgz)$ echo $ORG_ID
431498985862
michael@cloudshell:~ (pubsec-declarative-tk-apgz)$ gcloud alpha logging settings update --organization=$ORG_ID --storage-location=$REGION
ERROR: (gcloud.alpha.logging.settings.update) User [michael@approach.gcp.zone] does not have permission to access organizations instance [431498985862] (or it may not exist): Permission 'logging.cmekSettings.update' denied on resource (or it may not exist).
- '@type': type.googleapis.com/google.rpc.ErrorInfo
  domain: iam.googleapis.com
  metadata:
    permission: logging.cmekSettings.update
  reason: IAM_PERMISSION_DENIED
michael@cloudshell:~ (pubsec-declarative-tk-apgz)$ export EMAIL=$(gcloud config list --format json|jq .core.account | sed 's/"//g')
michael@cloudshell:~ (pubsec-declarative-tk-apgz)$ echo $EMAIL
michael@approach.gcp.zone
michael@cloudshell:~ (pubsec-declarative-tk-apgz)$ gcloud organizations add-iam-policy-binding "${ORG_ID}" --member "user:${EMAIL}" --role roles/logging.admin
Updated IAM policy for organization [431498985862].
bindings:
- members:
  - domain:approach.gcp.zone
  role: roles/billing.creator
- members:
  - user:michael@approach.gcp.zone
  role: roles/logging.admin
- members:
  - user:michael@approach.gcp.zone
  role: roles/orgpolicy.policyAdmin
- members:
  - user:michael@approach.gcp.zone
  role: roles/resourcemanager.folderAdmin
- members:
  - user:michael@approach.gcp.zone
  role: roles/resourcemanager.organizationAdmin
- members:
  - domain:approach.gcp.zone
  role: roles/resourcemanager.projectCreator
etag: BwXofMrmLtY=
version: 1
michael@cloudshell:~ (pubsec-declarative-tk-apgz)$ gcloud alpha logging settings update --organization=$ORG_ID --storage-location=$REGION
name: organizations/431498985862
storageLocation: northamerica-northeast1

```